# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gs/devel/bulk_email/MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 850)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/gs/devel/bulk_email/email.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tbwContacts = QtWidgets.QTableWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbwContacts.sizePolicy().hasHeightForWidth())
        self.tbwContacts.setSizePolicy(sizePolicy)
        self.tbwContacts.setObjectName("tbwContacts")
        self.tbwContacts.setColumnCount(2)
        self.tbwContacts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbwContacts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwContacts.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_3.addWidget(self.tbwContacts)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnNewContact = QtWidgets.QPushButton(self.centralWidget)
        self.btnNewContact.setObjectName("btnNewContact")
        self.verticalLayout_3.addWidget(self.btnNewContact)
        self.btnDelContact = QtWidgets.QPushButton(self.centralWidget)
        self.btnDelContact.setObjectName("btnDelContact")
        self.verticalLayout_3.addWidget(self.btnDelContact)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem)
        self.btnLoadContacts = QtWidgets.QPushButton(self.centralWidget)
        self.btnLoadContacts.setObjectName("btnLoadContacts")
        self.verticalLayout_3.addWidget(self.btnLoadContacts)
        self.btnSaveContacts = QtWidgets.QPushButton(self.centralWidget)
        self.btnSaveContacts.setObjectName("btnSaveContacts")
        self.verticalLayout_3.addWidget(self.btnSaveContacts)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.leSubject = QtWidgets.QLineEdit(self.centralWidget)
        self.leSubject.setObjectName("leSubject")
        self.horizontalLayout_5.addWidget(self.leSubject)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.tbwContent = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbwContent.sizePolicy().hasHeightForWidth())
        self.tbwContent.setSizePolicy(sizePolicy)
        self.tbwContent.setObjectName("tbwContent")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pteHtml = QtWidgets.QPlainTextEdit(self.tab)
        self.pteHtml.setObjectName("pteHtml")
        self.verticalLayout_5.addWidget(self.pteHtml)
        self.tbwContent.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pteText = QtWidgets.QPlainTextEdit(self.tab_2)
        self.pteText.setObjectName("pteText")
        self.verticalLayout_6.addWidget(self.pteText)
        self.tbwContent.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tbwContent)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lswAttachments = QtWidgets.QListWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lswAttachments.sizePolicy().hasHeightForWidth())
        self.lswAttachments.setSizePolicy(sizePolicy)
        self.lswAttachments.setObjectName("lswAttachments")
        self.verticalLayout.addWidget(self.lswAttachments)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnNewAttachment = QtWidgets.QPushButton(self.centralWidget)
        self.btnNewAttachment.setObjectName("btnNewAttachment")
        self.horizontalLayout.addWidget(self.btnNewAttachment)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnDelAttachment = QtWidgets.QPushButton(self.centralWidget)
        self.btnDelAttachment.setObjectName("btnDelAttachment")
        self.horizontalLayout.addWidget(self.btnDelAttachment)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.prbSending = QtWidgets.QProgressBar(self.centralWidget)
        self.prbSending.setMaximum(100)
        self.prbSending.setProperty("value", 0)
        self.prbSending.setObjectName("prbSending")
        self.horizontalLayout_4.addWidget(self.prbSending)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btnSend = QtWidgets.QPushButton(self.centralWidget)
        self.btnSend.setObjectName("btnSend")
        self.horizontalLayout_4.addWidget(self.btnSend)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1127, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionConfigure = QtWidgets.QAction(MainWindow)
        self.actionConfigure.setObjectName("actionConfigure")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionConfigure)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tbwContent.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tbwContacts, self.btnNewContact)
        MainWindow.setTabOrder(self.btnNewContact, self.btnDelContact)
        MainWindow.setTabOrder(self.btnDelContact, self.btnLoadContacts)
        MainWindow.setTabOrder(self.btnLoadContacts, self.btnSaveContacts)
        MainWindow.setTabOrder(self.btnSaveContacts, self.leSubject)
        MainWindow.setTabOrder(self.leSubject, self.tbwContent)
        MainWindow.setTabOrder(self.tbwContent, self.pteHtml)
        MainWindow.setTabOrder(self.pteHtml, self.pteText)
        MainWindow.setTabOrder(self.pteText, self.lswAttachments)
        MainWindow.setTabOrder(self.lswAttachments, self.btnNewAttachment)
        MainWindow.setTabOrder(self.btnNewAttachment, self.btnDelAttachment)
        MainWindow.setTabOrder(self.btnDelAttachment, self.btnSend)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BulkEmail"))
        self.label.setText(_translate("MainWindow", "Destinatari"))
        item = self.tbwContacts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tbwContacts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "E-mail"))
        self.btnNewContact.setText(_translate("MainWindow", "Nuovo"))
        self.btnDelContact.setText(_translate("MainWindow", "Elimina"))
        self.btnLoadContacts.setText(_translate("MainWindow", "Carica"))
        self.btnSaveContacts.setText(_translate("MainWindow", "Salva"))
        self.label_4.setText(_translate("MainWindow", "Oggetto"))
        self.label_2.setText(_translate("MainWindow", "Contenuto"))
        self.tbwContent.setTabText(self.tbwContent.indexOf(self.tab), _translate("MainWindow", "Html"))
        self.tbwContent.setTabText(self.tbwContent.indexOf(self.tab_2), _translate("MainWindow", "Testo"))
        self.label_3.setText(_translate("MainWindow", "Allegati"))
        self.btnNewAttachment.setText(_translate("MainWindow", "Nuovo"))
        self.btnDelAttachment.setText(_translate("MainWindow", "Rimuovi"))
        self.btnSend.setText(_translate("MainWindow", "Spedisci"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menu.setTitle(_translate("MainWindow", "?"))
        self.actionConfigure.setText(_translate("MainWindow", "&Configurazione"))
        self.actionExit.setText(_translate("MainWindow", "&Esci"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
